### ISSUE TITLE
Doc.: Broken 'The format is “[/]”.'

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#10150]
In the table row currently at 
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider-service,  the text says:
> The format is “[/]”.

and also
> The specification of is required only when it is insufficient to unambiguously resolve a service in the service registry.

and 
> The is a fully qualified host name of a service defined by the Kubernetes service or ServiceEntry. 

Those make no sense.

**Comment by ericvn** [comment]
I believe this was fixed in https://github.com/istio/api/pull/2034 which was not cherry-picked back to 1.10 (which is what istio.io is based on). Looking at https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider-service, this has been fixed in the 1.11 stream. `istio.io` website will move what is shown in `preliminary.istio.io` when 1.11 is released.

**Comment by ericvn** [comment]
Fixed now on istio.io. Please reopen if necessary.
