### ISSUE TITLE
Inconsistency issue labels between different repos

### ISSUE THREAD

**Issue by zirain** [istio/istio.io#12483]
In API repo:
![image](https://user-images.githubusercontent.com/4354057/213063147-c9b95ba4-87cf-40b9-b1e9-574db48fcffc.png)

In istio Repo:
![image](https://user-images.githubusercontent.com/4354057/213063199-270864da-1d60-4e65-a80e-261f5d0ed4ff.png)

cc @ericvn

**Comment by ericvn** [comment]
I will look into this. I know some repos like `ztunnel` are not getting updated either (they aren't in the list).

**Comment by ericvn** [comment]
Why are these labels different? The reason is that the bot has a number of autolabels that can be applied depending on what  is checked within the PR body when it's created. The current template has 

[ ] Extensions 

If this is checked the `area/extensions and telemetry` label would be added.

I suspect that the bot added a different label (old name) at the time it was created. Since no new PRs had that check box checked, there were no new PRs to get the new flavor of the label. created.

**Comment by ericvn** [comment]
I did look through the repos and made sure that the current autolabel `area/extensions and telemetry` is used consistently.

**Comment by ericvn** [comment]
I did create a PR, https://github.com/istio/bots/pull/639, which will hopefully cause the bot chron jobs to push the normal labels to the tunnel and enhancements repos.

**Comment by zirain** [comment]
it's ok for istio.io

![image](https://user-images.githubusercontent.com/4354057/220541566-807da0a9-be4f-4ef6-931f-55904e4151a1.png)
