### ISSUE TITLE
Add cleanup instructions to `istioctl analyze` page

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#12759]
Add cleanup instructions  for [`istioctl analyze`](https://istio.io/latest/docs/ops/diagnostic-tools/istioctl-analyze/) page

**Comment by johnma14** [comment]
Have few new contributors who can work on this.

**Comment by johnma14** [comment]
Need to add the cleanup section to: https://github.com/istio/istio.io/blob/master/content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md. (Similar to: https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/#clean-up-the-example)

```
kubectl label namespace default istio-injection-
kubectl delete ns frod
kubectl delete deployment my-deployment
kubectl delete vs ratings
istioctl uninstall --purge -y
kubectl delete ns istio-system

**Comment by hanxiaop** [comment]
Do we need clean up section for this page? Since `analyze` is analyzing existing configurations or configuration files, it's fine to use the feature anytime. Unlike 'Mutual TLS Migration,' which has specific configurations to work, analyze won't have such kinds of tasks to show, and doesn't need to apply any demo configs.

**Comment by johnma14** [comment]
@hanxiaop I am closing this issue. Thank you for clarifying.

**Comment by johnma14** [comment]
The `istioctl analyze` page does not install anything specifically but in the test.sh script it installs Istio (that install step is in that page) and deletes it by deleting the validating and mutating webhoook. That could be fixed, maybe.
