### ISSUE TITLE
Follow up work for get started guide - need to create a tab for k8s GW APIs

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#12803]
Following up work for https://github.com/istio/istio.io/pull/12783 review comment, we showed VS/DR in there, would be good to create a tab for k8s gateway resources as well

**Comment by danehans** [comment]
@linsun can you assign this issue to me?

**Comment by frankbu** [comment]
@danehans are you still planning to do this relatively soon? Now that the doc is tested (#12827), that will also need to be updated.

I can take a look at this, if you don't think you'll be able to get around to it soon.

**Comment by danehans** [comment]
@frankbu thanks for the follow-up. I'm working on my KubeCon EU talk this week. I plan to work on this issue next week. Feel free to assign yourself the issue if needed.

**Comment by danehans** [comment]
I have the Gateway API steps verified for the ambient getting started guide. I was hoping to achieve the steps with a minimal number of tabs but that's not the case. Each of the steps from [deploy the sample app](https://preliminary.istio.io/latest/docs/ops/ambient/getting-started#bookinfo) onward requires a separate tab due to slight differences in the deployment. For example, the current ambient guide uses `kubectl exec deploy/sleep -- curl -s http://istio-ingressgateway.istio-system/productpage | grep -o "<title>.*</title>"` to verify connectivity through the ingress gateway while the Gateway API tab will use `kubectl exec deploy/sleep -- curl -s http://bookinfo-gateway-istio.istio-ingress/productpage | grep -o "<title>.*</title>"`.

**Comment by danehans** [comment]
@howardjohn correct me if I'm wrong, but Istio's implementation of Kubernetes Gateway API does not support the Ambient [traffic splitting use case](https://preliminary.istio.io/latest/docs/ops/ambient/getting-started#control). If so, should I reference a design proposal or someone plans to support this use case for the Gateway API tab?

**Comment by howardjohn** [comment]
You can do the same with gateway-api today in Istio ambient mesh it just isn't documented there; gamma is experimental so we haven't been pushing it as hard

**Comment by frankbu** [comment]
Fixed by #12932
