### ISSUE TITLE
Need to make ambient more visible on istio.io home page

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#13478]
We should consider adding a banner on istio.io home page that says something like "Ambient is part of Istio 1.18 as alpha status, try it out!"

Need to research how to do this, but I think we have done it whenever we introduce a new release.

**Comment by ronitblenz** [comment]
It is very much possible. Would love to do that!

**Comment by mike-weiner** [comment]
Something like below? The Ambient banner would be displayed for the same period of time as the release banner - it would just have different content. 

![Screenshot 2023-07-26 at 7 38 55 PM](https://github.com/istio/istio.io/assets/47571709/99892b2f-66c4-428e-9f02-dd17057f4e28)

**Comment by ericvn** [comment]
I'm thinking you want to leave the .2 off, as it's part of all the 1.18 releases, not 1.18.2 (and later).

**Comment by ericvn** [comment]
My thoughts are to maybe make the duration longer (1 month) to get more converge. I might make the number of impressions a smaller number since the duration is longer (4?). Does it make sense to add a link, too https://istio.io/latest/news/releases/1.18.x/announcing-1.18/#ambient-mesh? as a link: maybe?

**Comment by mike-weiner** [comment]
Do we want this change to be merged into `master` or just `release-1.18`?

**Comment by craigbox** [comment]
Note from the future: we will revamp istio.io when Ambient reaches Beta.
