### ISSUE TITLE
Ambient usage guide is blank

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#13481]
https://preliminary.istio.io/latest/docs/ops/ambient/usage/ should explain how users can use ambient using bookinfo, which are pretty much covered in our get started guide.

Do we still need to do this page? @howardjohn

**Comment by howardjohn** [comment]
It should contain a lot more info. The other is demo/quickstart. We need to explain _how to operate ambient_. Things like how to attach policies to waypoints, when you should use a waypoint vs sidecar vs neither, etc IMO. 

Obviously an empty page isn't helping anyone right now, though :slightly_smiling_face: . But we do need more content

**Comment by srampal** [comment]
@linsun @howardjohn I could take a crack at this as a first issue.  Assigning to myself if thats okay ?

**Comment by srampal** [comment]
@howardjohn @linsun @keithmattix 

1) Please clarify how the desired content for the [page targeted for this PR](https://preliminary.istio.io/latest/docs/ops/ambient/usage/) is to be different from the [Ambient Getting Started page](https://preliminary.istio.io/latest/docs/ops/ambient/getting-started/) and what is the list of topics you would like to see added here.  
2) More broadly, should all docs content for Ambient be under the Istio->Operations->Ambient Mesh page only ? (which is the case now) or should pointers to Ambient also be present under other Istio sections such as Istio->Concepts or Istio->Setup etc ? Would be good to agree on a clear docs plan keeping those into account if needed. Please provide a summary of your desired high level content layout for Ambient and list of sub-topics. If easier, we can have a short call offline first to discuss.

**Comment by linsun** [comment]
@srampal we would love ambient content to be merged to usual istio page but when we started, we wanted dedicated page to  build our contents as it allow us to iterate faster.

For usage, I suggest us to have the following topics:

- mTLS, explain what is needed to configure this and which components are required. explain if mtls is enabled by default and if it is enforced always. (tie into the peer auth policy @keithmattix worked on).
- waypoint proxy, explain how to enforce L7 policy.
-- we could potentially cover a lot of L7 policies here from auth policy to traffic policy to some of the telemetry and wasm policy.
- explain when to continue use sidecars.

**Comment by srampal** [comment]
Started a WIP draft PR with a skeleton of the type of content to be added. Will add additional content based on feedback and discussions with the community on the documentation plan and structure. 

@howardjohn @linsun or anyone please provide your comments on the high level skeleton. 

https://github.com/istio/istio.io/pull/13635

**Comment by VibhorChinda** [comment]
Hi @linsun 😄  
Hope you're doing great.
I need some clarification around this project as it is included as an LFX project for the current cycle.
Can working professionals also be the part of this program :sweat_smile: ??

Some background about me, I am Vibhor a 2022 graduate from VIT Vellore.
Currently working with vSphere Solutions Team in VMware. [My current tech stack  : java, shell scripting]. Mostly my work is about automating new vSphere features for testing purposes.

I am trying to understand the cloud tech stack (Golang, Kubernetes, Docker) and contribute Kubernetes opensource community since quite some time now :eyes:

-  I am also the part of K8s v1.28 release Team as a Docs Shadow.
-  I was also the part of Cluster Api 1.4v release Team as a Docs Shadow.
-  I tried to contribute in kubernetes ecosystem solving some [beginner friendly issues](https://docs.google.com/document/d/1v91KvC34ByggqkrdVSQKESbkYZidRA04lYZG-1lOpUc/edit)
-  Documenting my learning journey about Kubernetes and Golang on my [Medium Profile](https://medium.com/@ChindaVibhor).
-  Volunteered as the Comms shadow for contributor summit '23.

If I am eligible, then I believe my above experience can be helpful for the documentation project.
Please reply whenever you're free 🙇🏻‍♂️

**Comment by vish-han** [comment]
@linsun @howardjohn I have seen this issue as a part of LFX Mentorship Fall' 23. I would love to work on this issue and have created Tech Documentation for the organization I have worked with.

**Comment by craigbox** [comment]
This issue has been [submitted for an LFX mentorship](https://mentorship.lfx.linuxfoundation.org/project/89ee4357-dd58-4e15-a601-c411742a587c).  If you're here to ask questions about it, please follow these steps:

* [learn about Istio and what it is](https://istio.io/latest/about/service-mesh/)
* [read the blog posts announcing Ambient Mesh](https://istio.io/latest/blog/2022/introducing-ambient-mesh/)
* look at what documentation there is for Ambient (not much!)
* install the sample
* note what you would have put in the documentation
* ask any questions in the Istio Slack on #docs.

Any other information for us should go into your application, which is submitted through the link above.  The best proposal will undoubtedly show that you've done some research, and know what you want to work on. We're sorry but we can't help write individual applications.

Good luck!

**Comment by ronitblenz** [comment]
I am interested to work on this project. I am currently a **Google Summer of Code Mentee**. I have experience with cloud native environment and also I am a **Cloud Native Community Group Chapter Lead** and volunteering at **Kubernetes Sig Contribex’s Comms in KubeCon Contributor Summit North America 2023**. I was privileged to be the only Under-20 to receive a Travel Scholarship from The Linux Foundation to attend **Open Source Summit Europe 2022 at Dublin, Ireland**. 

I have completed my tasks after application as well.
I would love to contribute for LFX Mentorship this season. 
Looking forward to add value.
Thanks in advance!

**Comment by krishnasvp** [comment]
@craigbox I would love to get started with working on this Issue as I am a Fall '23 LFX Aspirant, I am currently working on the steps mentioned above. I will come up with a good research and issue on the current site as well with respect to bugs, broken links etc..

**Comment by srampal** [comment]
@craigbox and anyone ... fyi, this issue was assigned to me and I am continuing to work on it. Since it was later also submitted for LFX mentorship after I was already working on it, I have broken down the work unto multiple sub-tasks and sub-guides so that multiple people can work on in addition to what I am doing. Currently we have multiple people working on the multiple sub-tasks already,  please check with me first for any further info and to avoid duplication of work.

**Comment by craigbox** [comment]
@srampal we quietly hoped you would agree to be the mentor for this issue 😁

**Comment by howardjohn** [comment]
fixed
