### ISSUE TITLE
F5 logo is too big

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#13574]
The largely horizontal nature of the images on our company logos (including front pages) makes the circular F5 logo stand out a bit too much.

<img width="1072" alt="Screenshot 2023-07-15 at 11 26 15 AM" src="https://github.com/istio/istio.io/assets/132510/f4880eda-3f81-4cd5-8c6f-cb8feb94b058">

Please use some CSS magic to make them visually equivalent.

Whatever we do also has to work well on https://istio.io/latest/about/ecosystem/.

**Comment by wilsonwu** [comment]
Seems not only F5 has a large logo:
![image](https://github.com/istio/istio.io/assets/1269496/169bbb4e-6197-4517-917b-bda20f6cb027)

**Comment by ericvn** [comment]
I suspect we limit the width so that the image doesn't pass horizontal or vertical bounds. A more square image will naturally scale larger in the square box. We likely need a more proportional images scaling. Not sure how to do the in our docs.

**Comment by mike-weiner** [comment]
@ericvn's suspicion that we are limiting the width to prevent the image from spilling out of the gray tile behind it is correct. He is also correct that there probably needs to be more proportional logo image files.

The short answer is that I don't think there is any great solution.

Each gray tile is a `company_logo` partial layout. These tiles have a `.company-logo` class that have padding to keep the image "inside" the gray background and display the logos in this grid fashion.

I tried setting a `max-width` property of `4rem` on the actual `<img>` tag, but this resulted in the exact opposite problem. (See the screenshot below.) The larger logos looked reasonably sized, but some of the smaller logs were way to small.

<img width="1367" alt="Screenshot 2023-07-27 at 4 06 06 PM" src="https://github.com/istio/istio.io/assets/47571709/17055ba6-50bb-4a73-832e-4c20463f0fa8">

My second thought was to create a second CSS class that we could add to logos to add some extra padding to reduce the large logo sizes. However, this won't work either since the `companies` partial layout has no information on the underlying size of the logo image files. We wouldn't want to do this anyways since it would have to be manually maintained.

I don't see any way (at least currently) where we could look at the dimensions of the image and then based on the ratio of image width to image height set the padding to try and keep the logos all approximately the same size.

**Comment by craigbox** [comment]
OK, thanks Mike - I think the action here is to upload an F5 logo with some padding built into the image, and then perhaps open an issue to revise the other logos later.  Some are much larger than others, but they don't immediately look out of place to me.

(BTW,  you have quickly rocketed to my favourite Istio contributor.)

**Comment by ericvn** [comment]
Pointer to an article that talks about this scaling: https://danpaquette.net/read/automatically-resizing-a-list-of-icons-or-logos-so-theyre-visually-proportional/

Adapting a set formula for resizing the images, as in the article, would be beneficial instead of random resizing to images.

**Comment by ericvn** [comment]
I will note that I couldn't find a way with the current layout to automatically apply this to each image as we display a page.
