### ISSUE TITLE
Update to snips did not really run all affected docs tests in CI

### ISSUE THREAD

**Issue by kfaseela** [istio/istio.io#14432]
See: https://github.com/istio/istio.io/pull/14362

This PR updated a snip, however the CI did not run another test file which was using the same snip and the PR got merged, breaking the automated tests. This had to be fixed in a separate PR later then.

https://github.com/istio/istio.io/pull/14415

Would be good to analyze the framework and see why the test was skipped.

**Comment by professorabhay** [comment]
Hey, @kfaseela! I would like to give it a try.
Is there any thing else that can help me to resolve it?

**Comment by leosarra** [comment]
Hello @kfaseela  and @professorabhay
This is happening because the [test file](https://github.com/istio/istio.io/pull/14415/files#diff-385b66c20ef1023b75033a588826b0a90eba80ae0c3cf61526fc9a3e903fb955) for egress-tls-origination was importing the snippets of egress-gateway-tls-origination tests via 
`source "content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh"`

"make gen" updated the snippets for egress-tls-origination and the tests that were present in the same folder as snips.sh, other tests that referenced an external snips.sh from another folder were not updated.

Shall we should consider this as "intended behavior of make gen" and discourage people from importing snips belonging to other tests? Or shall we update the make gen logic to try to handle this scenario?

**Comment by kfaseela** [comment]
> Hello @kfaseela and @professorabhay This is happening because the [test file](https://github.com/istio/istio.io/pull/14415/files#diff-385b66c20ef1023b75033a588826b0a90eba80ae0c3cf61526fc9a3e903fb955) for egress-tls-origination was importing the snippets of egress-gateway-tls-origination tests via `source "content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh"`
> 
> "make gen" updated the snippets for egress-gateway-tls-originatio and the tests that were present in the same folder as snips.sh, other tests that referenced the updated snips.sh from another folder were not updated.
> 
> Shall we should consider this as "intended behavior of make gen" and discourage people from importing snips belonging to other tests? Or shall we update the make gen logic to try to handle this scenario?

@ericvn what do you think?

**Comment by leosarra** [comment]
The presubmit did not run those tests because the current logic for the presubmit job is to run tests in folders whose tests.sh or snippet.sh file have changed.
Considering that "make gen" only updated the snippet and tests in egress-gateway-tls-origination folder while not performing any changes for the egress-tls-origination folder (whose tests.sh imported the egress-gateway-tls-origination snippets), it explains why the egress-tls-origination were skipped (as no changes were performed there)

The way to handle it is to update "scripts/pr_tests.py" file to also run tests which have used "source $path_to_imported_file" in their tests.sh/snippet.sh in case the imported_file has changed as part of the PR.
The alternative would be to discourage tests importing other tests snippets.

If we go for the changes I can quickly update the pr_tests.py

**Comment by kfaseela** [comment]
> The presubmit did not run those tests because the current logic for the presubmit job is to run tests in folders whose tests.sh or snippet.sh file have changed. Considering that "make gen" only updated the snippet and tests in egress-gateway-tls-origination folder while not performing any changes for the egress-tls-origination folder (whose tests.sh imported the egress-gateway-tls-origination snippets), it explains why the egress-tls-origination were skipped (as no changes were performed there)
> 
> The way to handle it is to update "scripts/pr_tests.py" file to also run tests which have used "source $path_to_imported_file" in their tests.sh/snippet.sh in case the imported_file has changed as part of the PR. Keep in mind that we may have to also handle the scenario where a snippet or test imports from another which in turn imports from yet another snippet etc etc. The alternative would be to discourage tests from importing other tests snippets and update the existing ones.
> 
> If we go for the changes I can quickly update the pr_tests.py

@ericvn what do you suggest?

**Comment by leosarra** [comment]
This is my draft for the needed changes #14443
It computes a dependency graph and it uses it to detect which additional tests need to be executed

**Comment by ericvn** [comment]
I suspected the logic was only checking the local directory, and that we would have to look at the source statements if we wanted to fix this going forward. Thanks @leosarra for verifying that behavior. AS noted, I don't think we want to discourage the source, so trying to verify the dependency would be my preference to fix. I'll look at the changes proposed shortly.
