### ISSUE TITLE
Need to doc and show users how to verify mtls is enabled in ambient.

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#15486]
Currently it is not very clear. Our get started guide uses kiali dashboard but that is not automatable and not everyone uses kiali.

Other way is use L4 metrics or ztunnel logs with src and dest identities (each has its spiffe id): https://istio.io/latest/docs/ambient/usage/troubleshoot-ztunnel/#verifying-ztunnel-traffic-through-logs.

@howardjohn also mentioned: https://github.com/istio/istio/discussions/52014

**Comment by linsun** [comment]
cc @craigbox

**Comment by bleggett** [comment]
Is there a difference between 

`pod enrolled in ambient`

and 

`mtls enabled for pod enrolled in ambient`


outside of very large Istio bugs, isn't that a Venn diagram with completely overlapping circles?

**Comment by craigbox** [comment]
What we have is "omg, this is magic", and what we need is some way of showing an operator that this isn't smoke and mirrors.

I brainstormed this with @peterj a while back and he realised the idea with https://github.com/peterj/ambient-mtls-demo

**Comment by bleggett** [comment]
> What we have is "omg, this is magic", and what we need is some way of showing an operator that this isn't smoke and mirrors.
> 
> I brainstormed this with @peterj a while back and he realised the idea with https://github.com/peterj/ambient-mtls-demo

:+1:  - if we want to prove it to people, it needs to be connection-level _and_ involve actually checking packets - zt logs and control plane status are both the wrong tools for that, and we already have the annotation for the workload-level - which is all any tooling or things like Kiali or the majority of our docs should look at.

**Comment by craigbox** [comment]
I'm not sure people want to verify it with bookinfo?  
Plus I do like the fact Peter's script has passwords you can see flowing past - bookinfo doesn't have that.

We could bring it into Istio as a sample?

**Comment by linsun** [comment]
Could we just show people the L4 metrics where it has mtls and spiffee ID of source and destination? Most users want to verify it with their own app, rather than a specific sample we provide imho.

**Comment by howardjohn** [comment]
My 2c - there is no one answer. 

There are a few (overlapping) questions we need to let users answer:
* Is my app sending and receiving mTLS traffic? Possibly, to/from which peers?
* Is my app *only* accepting mTLS traffic (STRICT mode)

What answers are acceptable differs based on the persona.

* If I am just making sure I configured things correctly, a command showing the configured state is sufficient (`istioctl zc workloads` or equivilent).
* If I am seeing weird behavior and debugging, I don't want the _configured_ state but also the actual state at the lowest layer of the system
* If I am trying to identify a specific set of traffic is mTLS, I may want to observe the traffic is mTLS from metrics/logs
* If I want to continuously monitor and alert, I very likely want metrics
* If I am a strict auditor, I may not trust **any** of the above and only trust more invasive checks like TCPDump, actually sending TLS handshakes/non-TLS and observing their behavior, etc. A less strict auditor may be fine with some of the above steps.

All of these are important personas to handle, and well worth solving. The key value proposition of ztunnel is zero-trust, it would be a shame to have users install our software and not be able to verify its doing anything.

**Comment by bleggett** [comment]
> Could we just show people the L4 metrics where it has mtls and spiffee ID of source and destination? Most users want to verify it with their own app, rather than a specific sample we provide imho.

Connection level metrics would be good, but "I want connection-level metrics" is != "I want to know if mTLS is enabled".

Depending on what you mean by `enabled`, connection metrics are either too detailed or prove nothing.

> My 2c - there is no one answer.

Yep. I suspect it's 2 answers, and a slightly-wrong question which people are used to asking in a sidecar context, but which is less valuable to ask in an ambient context:

"Is mTLS being used"
- Workload-level (config/CP status, effectively)
- Connection-level (are packets being encrypted, DP, I need to prove to myself the CP isn't lying to me or misconfigured)

- Connection metrics (we should have these for many other reasons, but their primary purpose is not to "verify if mTLS is enabled").

 Unlike with sidecars, there currently is no state where mTLS _to or from_ a specific workload is conditional - we have no capture op-outs - so looking at connections instead of workloads to "show" mTLS state is a bad habit we need to break users of, albeit slowly.
 
- If you wanna prove something about the CP state of workloads - we have that already.
 
- If you wanna prove something about whether packets are encryped - we can give you a simple and unambiguous way to show that.

If you want something else, you're probably asking a question that has meaning in a sidecar context but is mooted in an ambient context.

**Comment by ilrudie** [comment]
> Unlike with sidecars, there currently is no state where mTLS to or from a specific workload is conditional - we have no capture op-outs - so looking at connections instead of workloads to "show" mTLS state is a bad habit we need to break users of, albeit slowly.

Your WL may be opt-in/captured/working but not strict. A pod from outside your namespace connects to it, is it mTLS? Seems reasonable to ask and you may not have permissions to look at their namespace or istio-system to answer the question by checking config state.

**Comment by bleggett** [comment]
> Your WL may be opt-in/captured/working but not strict. A pod from outside your namespace connects to it, is it mTLS?

The answer to this in an ambient context ATM is unconditionally "no it is not" - correct?

**Comment by bleggett** [comment]
> Your WL may be opt-in/captured/working but not strict. A pod from outside your namespace connects to it, is it mTLS? Seems reasonable to ask and you may not have permissions to look at their namespace or istio-system to answer the question by checking config state.

If the CP knows about it, it is mTLS, and if it doesn't, it's `unknown` and not, from ambient's perspective - no?

**Comment by ilrudie** [comment]
yeah, options that exist now are pretty slim to handle this situation:
- potentially you could look at metrics some where if they are collected and you have permissions
- ztunnel mds impl that has been proposed would be accessible to you

**Comment by bleggett** [comment]
> ztunnel mds impl that has been proposed would be accessible to you

If we have some way for a pod to introspect its own connections yea - but again if you have perms to know what the other workload is, you already know the answer. 

And if you don't, we probably shouldn't tell you?

Which means you're back to "I can check the packets to see, or I can rely on the control plane to tell me", AFAICT.

**Comment by howardjohn** [comment]
I would rather have a doc with 5 ways to look at it then with 1 way that we have all bikeshed to hell as the "best" way to view it. Because we are never going to pick the 'best' way from the users perspective. Obviously we can recommend one.

For example, tcpdump is a good solution for some set of users... unless they don't have network admin access. Now we need the next best solution.

**Comment by bleggett** [comment]
xref with: https://github.com/istio/istio/issues/48651

(which is IMO a slightly different problem, but it would be nice for tests + doctests + "prove it to yourself guides" to use the same mechanism if possible)

**Comment by linsun** [comment]
Agreed, let us get the content out and we can iterate on it over time. Any volunteers? If not, I can look into it later this week.

**Comment by keithmattix** [comment]
I think this is done
