### ISSUE TITLE
scrolling issue in long pages with lots of headings

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#15519]
See https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-ztunnel-config-service

If you start scrolling in the TOC pane (starting with "Parameters") then you only get as far as "ztunnel-config workload", which is also as far as I could get with my scroll wheel.

<img width="1598" alt="Screenshot 2024-08-06 at 4 20 47 PM" src="https://github.com/user-attachments/assets/c12a6738-aa2a-40df-b2da-f4ba21086349">

Scroll far enough down the page with the actual page scrollbar, and you can see the two other headings that are below it:

<img width="1369" alt="Screenshot 2024-08-06 at 4 20 28 PM" src="https://github.com/user-attachments/assets/b5be719c-fea9-4606-a417-68cc10167d49">

**Comment by mike-weiner** [comment]
For someone who might tackle this, I did spend a few minutes poking around. 

I suspect this is due to the sticky positioning being used to keep the table of contents (TOC) in the same position on the page as you scroll down the page to make it easier to jump around to different sections on the page.

Removing the top padding on the TOC `div` (change (b) in the screenshot below) and adjusting the `top` positioning to use `vh` (change (a) in the screenshot below) to move the starting position of the `div` farther down the page while also reducing the max-height of the TOC `div`(change (c) in the screenshot below) accomplishes the same thing. These changes ensure that you can scroll to the bottom of the TOC list and see all items. 

I did not explore how this change behaves on larger screen sizes or mobile devices. I suspect that this TOC `div` is a reusable component, so other pages that use this component will need to be evaluated to see how this change impacts the look and feel on those pages.

Anyways, likely a good starting point for more investigation. 

![Screenshot-2024-08-07-08 28 08PM](https://github.com/user-attachments/assets/cc150a34-470c-4537-9579-94be7e90993a)
![Screenshot-2024-08-07-08 28 25PM](https://github.com/user-attachments/assets/735edda2-c322-4d5e-9b1e-6ff851609a9a)
