### ISSUE TITLE
fr: integrate scss into Hugo

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#16009]
Change to having Hugo compile the CSS, so that I don't have to break out of the preview and run `make site` every time I change anything.

**Comment by mike-weiner** [comment]
I'm sure Hugo has some way to watch & recompile the CSS, but I suspect the directory structure of this repo would have to change, so I didn't spend too much time looking into that. 

We could accomplish this fairly easily with `sass` directly via adding the below to `Makefile`:
```
watch-sass:
	@sass --watch src/sass/_all.scss generated/css/all.css -s compressed --no-source-map
```

I tested this locally: 

1. Ran `make serve` to start the Hugo web server.
2. In a separate terminal window ran `make watch-sass`. 

After I made a CSS change, `sass` detected the change and re-complied. A refresh of my browser a second or two later showed the change. 

I ran into problems adding this command to `Makefile.core.mk` because of the `BUILD_WITH_CONTAINER` option present in `Makefile`. 

We want `make serve` to continue to run in a container, but we don't need the `sass` command to be in a container. 

This still isn't a very elegant solution.

**Comment by craigbox** [comment]
This has worked for me, per [Hugo docs](https://gohugo.io/hugo-pipes/transpile-sass-to-css/):

* move the `sass` directory from `src` to `assets`
* edit `baseof.html` and replace the existing stylesheet link with something like:

```
        {{- $opts := dict "transpiler" "libsass" "targetPath" "css/style.css" -}}
        {{- with resources.Get "sass/_all.scss" | toCSS $opts | minify | fingerprint -}}
        <link rel="stylesheet" href="{{ .RelPermalink }}" integrity="{{ .Data.Integrity }}" crossorigin="anonymous">
        {{- end -}}
```

Then, when one of the `.scss` files was changed, Hugo noticed and recompiled.  It didn't live reload the page but a reload did as expected and it's a million times more useful for the one time every 5 years I try this!

I'll send a PR.

In theory we should be able to remove this from the Makefile, and possibly also [replace the Babel JS bundling](https://gohugo.io/hugo-pipes/js/).

**Comment by mike-weiner** [comment]
Oh, nice! I was unsure if moving the sass out of `src` and into `assets` might break any of the existing tooling that is used to build and publish the site. 

Having CSS rebuild like this will be awesome!

**Comment by craigbox** [comment]
I don't think it will, but that's what branch previews are for 😁
