### ISSUE TITLE
GCP services don't work with VirtualService

### ISSUE THREAD

**Issue by rvandegrift** [istio/istio.io#2645]
According to https://istio.io/docs/tasks/traffic-management/egress/ an external HTTPS service requires a ServiceEntry and VirtualService.  I couldn't get the GCP API to work with the configuration in that document.

I was able to fix it by creating an HTTPS ServiceEntry for `*.googleapis.com` on port 443, and removing all of the `VirtualService` entries.

**Comment by frankbu** [comment]
The `resolution` of a `ServiceEntry` needs to be `NONE` if the host is a wildcard, because the proxy won't resolve `DNS` in that case. https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-Resolution

That said, I think the `VirtualService` is not actually needed in any simple passthrough ServiceEntry (wildcard or not). Probably needs to be clarified in the egress doc.

**Comment by andraxylia** [comment]
Maybe for SNI? @vadimeisenbergibm any idea?

**Comment by rvandegrift** [comment]
Now I'm confused - my current pods seem to work with `*.googleapis.com` and `resolution: DNS`.  At least for `pubsub.googleapis.com` and `logging.googleapis.com` I don't see any problems.  But @frankbu is right, the docs appear to say that this cannot work.

Stepping back what's the intended developer experience here?
* Do I individually create `ServiceEntry` objects for each cloud service endpoint that I use?
* Can these be created once per service mesh, or must every Istio-enabled service add them?
* If they can be created centrally, what happens if multiple develoeprs create them?

The docs could use some real-world examples that address these questions.

**Comment by andraxylia** [comment]
It will work with both resolution NONE and DNS, but do an extra DNS lookup if DNS is used, based on the actual host header.

Assume a call to translate.googleapis.com: client app does a DNS lookup , resolves to IP x.x.x.x and sends the packet to Envoy with dest IP x.x.x.x and host "translate.googleapis.com".

For resolution NONE: we configure orig dest IP, so packet is sent to x.x.x.x

For resolution DNS: we configure a 0.0.0.0 listener and a cluster with DNS. Envoy performs DNS lookup on  "translate.googleapis.com", which comes back as x.x.x.x. Packet is sent to x.x.x.x

@rvandegrift thanks for the feedback, we plan to keep improving the docs as we go.
For your questions:
- 
Q:"Do I individually create ServiceEntry objects for each cloud service endpoint that I use?"
A: For access to external services, you do not need to create one ServiceEntry for each external service you need to access, that would be onerous. Unless you want to restrict access. The way you did it using domains is perfect. This allows external access , but controls it by individual host or domain.
If you need full access, you can use the include IP Ranges option:
https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly

- 
Q:"Can these be created once per service mesh, or must every Istio-enabled service add them?"
A: They are once per mesh, and not directly related to any other Istio service (if you look in the config , there is nothing to refer to an existing Istio service). ServiceEntries are in fact siblings of Services defined natively in the platform, they allow to add external services or other in-mesh services located in other clusters/platforms.

- 
Q:"If they can be created centrally, what happens if multiple developers create them?"
A: For multiple ServiceEntries to the same host or domain, we should merge the endpoints. Not sure if this is implemented yet @rshriram  @costinm

**Comment by andraxylia** [comment]
Merging ServiceEntries is also needed for multi-cluster.

**Comment by andraxylia** [comment]
Still unclear when do we use SNI for external, since this is configured in the VirtualService in the current documentation, and I see istio/istio#3876 mentioned SNI as a solution.

cc @ostromart @loewenstein

**Comment by rshriram** [comment]
Sorry for the sloppy documentation. I can't comment on why DNS works until I see the full service entry spec. 
In terms of dns resolution, if you specify resolution as DNS, then envoy will do dns resolution periodically, and route to one of the endpoints returned by the DNS. DNS is not resolved for each request. If you use resolution NONE, then envoy will use the IP address that the application provides (obtained by DNS or whtever).

If you have a wildcard host and no endpoints, then the only way traffic will flow is when the resolution is NONE. Envoy will not do dynamic DNS resolution based on the host header.

We do not merge service entries. If multiple people define the same service entry, the behavior is undefined. I suggest you put all your service entries in one common namespace, so that you can atleast deduplicate service entries during submission.

**Comment by frankbu** [comment]
> If you have a wildcard host and no endpoints, then the only way traffic will flow is when the resolution is NONE. Envoy will not do dynamic DNS resolution based on the host header.

@rshriram I noticed the same behavior that @rvandegrift mentions above, it does seem to work with `resolution: DNS`. What exactly does Envoy do if wildcards are use in the DNS case? Instead of sending an error response when there's no sni, does it maybe first check if there is a resolved destination IP from application and use it? That would explain what's happening wouldn't it?

**Comment by rshriram** [comment]
I don't think its envoy.. somewhere in Pilot, we are ignoring the DNS and setting it as NONe if the host has wildcards

**Comment by rvandegrift** [comment]
Here's my config that's working with `pubsub.googleapis.com` and `logging.googleapis.com`:
```sh
$ istioctl -n fly-points get virtualservice
No resources found.
$ istioctl -n fly-points get serviceentry
SERVICE-ENTRY NAME   HOSTS              PORTS       NAMESPACE    AGE
googleapis           *.googleapis.com   HTTPS/443   fly-points   8d
$ istioctl -n fly-points get serviceentry googleapis -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  creationTimestamp: null
  name: googleapis
  namespace: fly-points
  resourceVersion: "6344656"
spec:
  hosts:
  - '*.googleapis.com'
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
```

If this permits all cluster-external traffic on port 443, that's great for me - so long as it still enforces mutual TLS inside the cluster.

**Comment by vadimeisenbergibm** [comment]
Back from vacation, did not see this issue earlier, sorry.

@rvandegrift Please note that as @rshriram wrote:
>  If there is no virtual service, we will treat the port as a original destination port (443). This means, the application could access any arbitrary site (yahoo.com) over 443 and traffic will flow. If you specify a virtual service, then you can restrict the flow to those hosts defined inthe service entry.

So while your `ServiceEntry` allows access to `*.googleapis.com`, it also allows access to `yahoo.com`, which you may not want. You may want to define a `VirtualService` to limit access to `*.googleapis.com` only.

**Comment by rvandegrift** [comment]
@vadimeisenbergibm With `VirtualService` entries for e.g. `pubsub.googleapis.com`, pods were not able to connect.  At this point I forget the details of the deployment - I'm currently traveling, but will try to get a test case put together next week.

**Comment by rvandegrift** [comment]
I did some testing today on a fresh GKE 1.10.7 cluster & Istio 1.0.2.  I was able to get `*.googleapis.com` working in ServiceEntry and VirtualService as expected.  Not sure what the original issue was.

I did discover some problems/unexpected behavior with wildcard ServiceEntry and VirtualService objects.  But I'll open a new issue for that.

**Comment by andraxylia** [comment]
@rvandegrift please cc me in the new issue.
