### ISSUE TITLE
Translate to Japanese

### ISSUE THREAD

**Issue by chaspy** [istio/istio.io#3004]
Thank you for a great document. It is very useful.

I would like to contribute to translating into Japanese,
but do I have anything to consider?

As shown by `content/OWNERS`, do I need to gather member to approve?
Or just create `content_ja` directory and send a PullRequest?

**Comment by geeknoid** [comment]
Just start sending some pull requests, we'll set up OWNERS and other minor things as we go.

Note that the documentation set is constantly evolving, and is pretty large. Translating the site and keeping it up to date ends up being a long-term on-going effort. It's therefore useful to have a community of translators, that can pitch in and review each other's translations.

**Comment by rootsongjc** [comment]
@chaspy This is really a large site, it has taken us a long time to keep updated with the Enligsh version, the Chinses version is maintained by [ServiceMesher community](http://www.servicemesher.com) and issues are tracked [here](https://github.com/servicemesher/istio-official-translation/issues), that may give you a sense about the job.

**Comment by chaspy** [comment]
@geeknoid @rootsongjc 
Thanks for your advice!
Certainly this document has huge volume and it seems difficult to follow the original change...

But let me send the first PullRequest.
and I consider the community for maintainers.

**Comment by fleeto** [comment]
Hi @chaspy , Here is [some code for the Chinese translation](https://github.com/fleeto/slackbot/blob/master/src/plugins/mesherbot/gitscan.py), It will  find updated file since last translated version. I hope It can help you to find the updated files.

And a [Webhook](https://github.com/fleeto/issueflow), which help us to manage translation tasks, It's now running for both k8s and istio translation groups in China.
