### ISSUE TITLE
Kiali instructions need an update

### ISSUE THREAD

**Issue by arun-gupta** [istio/istio.io#3035]
Using Kiali instructions:

https://preliminary.istio.io/docs/tasks/telemetry/kiali/

Following updates need to be made:

- These instructions are for 1.1. Should be shown for 1.0.5 as well.
- KIALI_USERNAME and KIALI_PASSPHRASE are not required if Kiali is installed using Istio Helm charts. They have a pre-built username and passphrase. This needs to be clarified.
- Kiali UI is available at http://localhost:20001/, not http://localhost:20001/kiali.

FYI @christian-posta

**Comment by jmazzitelli** [comment]
Yes, these instructions are directed specifically towards Istio 1.1 because, AFAIK, these "preliminary" docs are for Istio 1.1 specifically. I don't know what the policy is for introducing 1.0-only instructions in the preliminary docs. @rcaballeromx can you elaborate on this? Specifically, the preliminary docs - are they for 1.1 only?

This is why we added /kiali to the instructions for the http://localhost:20001 URL - see https://github.com/istio/istio.io/pull/2885 for the PR where we added the "/kiali" context root in the docs due to this PR that went into istio 1.1: https://github.com/istio/istio/pull/9588

The credentials are required for 1.1 even when installing via helm. We removed any pre-defined credentials in istio 1.1 that were in istio 1.0 - for example, see https://github.com/istio/istio.io/pull/2841
And because the preliminary docs are only for 1.1 (AFAIK) these docs do not talk about the 1.0 instructions for the out-of-box credentials.

**Comment by arun-gupta** [comment]
Now that Kiali is integrated in 1.0.x as well, at least a working version of the docs should be posted there.

**Comment by christian-posta** [comment]
Can someone comment on whether Kiali is "officially" the Istio web console in 1.0.x? I know there was some discussions where it would be for 1.1. Is that why it's not in the 1.0.x docs? Should we add it? Until 1.1 comes out, folks will be confused about how to install/interact with Kiali in the 1.0.x distro of Istio.

**Comment by jmazzitelli** [comment]
I think we should put some kiali docs in the 1.0 istio docs. Now that 1.1. has been pushed out, we really need to get some official docs available to people. I think we didn't put it in the 1.0 doc set because 1.1 was going to come out in October originally and we figured it made sense to introduce Kiali in that documentation. But now that 1.1 has been pushed, and Kiali has been in istio 1.0 for a while now, I think it makes sense to put something in 1.0 docs.

**Comment by jmazzitelli** [comment]
See this PR I created: https://github.com/istio/istio.io/pull/3062

If we want Kiali in the Istio 1.0 docs, that PR will introduce the Kiali Task. Would require someone to review/merge that PR.

**Comment by jmazzitelli** [comment]
docs have been added to 1.0 to help address this issue. See:

https://istio.io/docs/tasks/telemetry/kiali/

**Comment by geeknoid** [comment]
So do we need to do anything more here, or can this issue be closed?

**Comment by jmazzitelli** [comment]
> So do we need to do anything more here, or can this issue be closed?

nothing unless @arun-gupta wants to review the docs

**Comment by arun-gupta** [comment]
In the docs, Kiali secrets are really optional. There is a default username/password that works and I think that should be the one shown as that provides a simplified user experience. The docs should show the current experience and be updated when that changes.
