### ISSUE TITLE
Need to update helm instruction with correct repo before 1.1 live

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3131]
The current helm instruction is wrong where it didn't ask users to do the repo add and dep update cmd, examples:

```
 helm repo add istio.io https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
helm dep update install/kubernetes/helm/istio
```

This needs to point to a released repo.  cc @hklai

**Comment by hklai** [comment]
@linsun @geeknoid 
I suppose https://github.com/istio/istio.io/blob/master/content/docs/setup/kubernetes/helm-install/index.md needs to be updated when 1.1.0 is tagged.

We have automated a similar update in https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/README.md in the release scripts (i.e. the README.md is shipped in the tarball)

For istio.io docs, I am not sure if it is worthwhile to send an automated PR to update it (in the right branch).

**Comment by linsun** [comment]
@hklai yes good point on the index.md file.  

Manual is fine... wanted to open this so we remember this before releasing 1.1.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by geeknoid** [comment]
@linsun Can you take care of this?

**Comment by linsun** [comment]
waiting on official 1.1 is published to update the url.

**Comment by duderino** [comment]
@sdake @linsun @ostromart @geeknoid this means 1.1 published in a helm repo.  Who should do that?

**Comment by sdake** [comment]
@duderino the release manager (@hklai) did this in the past.  It was pretty much automated afaik.  This can lag Friday a few days if it takes some time to sort out.

**Comment by sdake** [comment]
@duderino the reason this can lag is because the instructions that referenced the istio.io repo were removed in PR: https://github.com/istio/istio.io/pull/3689#issuecomment-473051635.  TLDR - we are producing an SRE guide in the documentation WG that delivers helm charts via this mechanism.

Some developers have still grown fond of the technique of using helm as a distribution mechanism, so we will need these packages prior to the SRE guide.

Recommend moving to a P1.  @linsun agree?

Cheers
-steve

**Comment by frankbu** [comment]
I would suggest closing this issue because, as @sdake mentioned, we no longer reference the helm repo in the helm install instructions (PR: #3689) so nothing else is needed before 1.1 goes live.

Let's open a different issue for the SRE guide with repo-based helm installation instructions. This one should be high priority for after 1.1 goes live.

**Comment by linsun** [comment]
Looking at the latest doc, I concur we no longer uses helm repo in our helm install doc.  Agreed, we can close this.

**Comment by tiswanso** [comment]
@sdake @frankbu @linsun  Do the instructions exist now for Istio release helm repo usage in the SRE guide that is mentioned here?  The changes to remove the instructions for the Istio release helm charts in #3689 break the Istio CNI install instructions.

Was there circular reasoning in closing this bug?  #3689 went in because the helm repo instructions were being tracked by this bug and it looks like this bug was closed because #3689 no longer has helm repo instructions. :-)

**Comment by frankbu** [comment]
@tiswanso #3689 went in because it makes more sense for the majority of users those instructions are targeting.

What is broken in the CNI install instructions. Can they be updated to work with the charts in the release image, or do they need to use the helm repo for some reason?

**Comment by tiswanso** [comment]
@frankbu --not arguing what makes sense or not for the Istio helm install page.  IMHO, it was very late to change the main helm instructions to include removal of all use of the actual helm repo test-and-release publishes.  Regardless, the CNI install instructions breaking were collateral damage since they were written building on the prior Istio helm install instructions which were based on using helm repo.  For consistency and to avoid duplication, the CNI install instructions are necessarily dependent on the Istio install instructions.
