### ISSUE TITLE
Improve the links checker's performance locally and on CircleCI

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#3438]
The links checker can take up to 4 minutes to complete with CircleCI and, depending on machine, it takes twice as long to complete.
This makes organizing and updating content needlessly time consuming.

**Comment by geeknoid** [comment]
We use htmlproofer for link checking. htmlproofer has a cache such that if it validates a link once, it won't try to validate it again for 2 days. Unfortunately, this cache cannot be used in CircleCi. But it should be used locally when you run lint yourself.

**Comment by geeknoid** [comment]
htmlproofer can run in parallel, but we're not using this option at the moment since there is no command-line option for it, it can only be controlled through a Ruby config file. It'd be good to figure out how to turn this on in order to speed things up.

The README file in the GitHub repo for html-proofer has the details on the parallel option.

**Comment by rcaballeromx** [comment]
Thanks @geeknoid I'll take a look once I'm done with the restructure we discussed on the WG.
