### ISSUE TITLE
Incorrect chart name for installing w/ Helm and Tiller

### ISSUE THREAD

**Issue by m-eaton** [istio/istio.io#3458]
After first adding the istio.io repo in the [Installation steps](https://preliminary.istio.io/docs/setup/kubernetes/install/helm/#prerequisites) and then following the steps in [Option 2](https://preliminary.istio.io/docs/setup/kubernetes/install/helm/#option-2-install-with-helm-and-tiller-via-helm-install) to install Istio 1.1 with Helm and Tiller, I get an error on step 5:

```bash
$ helm install istio --name istio --namespace istio-system
Error: failed to download "istio" (hint: running `helm repo update` may help)
```

This can be fixed by updating the chart path from `istio` to `istio.io/istio`:
`helm install istio.io/istio --name istio --namespace istio-system`

**Comment by m-eaton** [comment]
Related to istio/istio#12081

**Comment by sdake** [comment]
@m-eaton thanks for filing the bug and correcting this problem.  Sadly I didn't see this was fixed by you and submitted a PR sunday which was merged here: https://github.com/istio/istio.io/pull/3483.

Since this issue is fixed, I am closing this issue.  Thanks again for the contribution and hopefully we will have less duplication of work in the future (my bad).

**Comment by duderino** [comment]
@m-eaton Thank you for the contribution.  Sorry for the mixup
