### ISSUE TITLE
platform install page left side navigation too long

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3590]
https://preliminary.istio.io/docs/setup/kubernetes/install/platform/

I noticed the left side navigation is really long.  Could we shorten it to just the platform name?  Does the title of the page have to match what is on the left side navigation?

cc @geeknoid @rcaballeromx

**Comment by geeknoid** [comment]
@rcaballeromx Can we shorten the names a bit?

I'll have to check, but I think it you use:

titlte: my doc titlte
linktitle: shorter

Then the shorter name will be used in the sidebar.

**Comment by geeknoid** [comment]
Yep, it works. If you use linktitle: you can force the text in the sidebar to be different.

It'll also affects the text use for the left-right arrows at the bottom of each page, as well as in the breadcrumb at the top of each page.

**Comment by rvennam** [comment]
I noticed that things are just generally bigger in preliminary. This includes the font-size for body and headings... causing lots of wraps and multi-line titles. Is this change intentional? 

<img width="1324" alt="Screen Shot 2019-03-08 at 4 26 28 PM" src="https://user-images.githubusercontent.com/5502967/54056727-f619fa00-41be-11e9-9bf6-9e6d9a44e041.png">

**Comment by geeknoid** [comment]
It's possible I messed up the styles and the fonts are different sizes than
before, I'll check it out.

The sidebar has actually more room than before due to tuned layout. So it
should be wrapping less than in 1.0.

However, there's only so much one can do with formatting. Some of our
titles just need to be cut down and less engineer literal-minded
geek-speak. It's OK to leave some of the meat of the page in the content,
it doesn't have to all be crammed into the title :-)

**Comment by geeknoid** [comment]
@rvennam I've just compared several pages between istio.io and preliminary.istio.io and I don't see any font size differences, except for the headers in the left-hand sidenav.

Can you point out specifically where you see differences?

**Comment by rvennam** [comment]
@geeknoid I was mistaken - I had the zoom set to 90% on istio.io :)

**Comment by geeknoid** [comment]
Fixed by #3603
