### ISSUE TITLE
Api proto doc ISTIO_META_INTERCEPTION_MODE displays mixed italic in html

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#3638]
The symbol ISTIO_META_INTERCEPTION_MODE in the proto doc here:

https://github.com/istio/api/blob/75f0c6603d0b9118dd23df09ce5d26fae5d68f04/networking/v1alpha3/sidecar.proto#L106

Produces a strange mixed italic symbol in the generated html: ISTIO _META_ INTERCEPTION_MODE

https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/

**Comment by geeknoid** [comment]
The markdown parser is treating the underscores as introducing _italics_. Put the symbol in backticks and the problem should go away.

**Comment by geeknoid** [comment]
Note that I've turned on spell checking support in the istio/api repo and it would flag this as a typo. We just need to fix all the spell check errors and then we can turn it on as a checkin gate.

**Comment by geeknoid** [comment]
If you search for instance of `<em>` in content/docs/reference/*.html, you'll find all the oddball cases where incorrect italicizing is taking place, along with with a few legitimatish cases. Some of these cases (like `_percentage_`) actually need to be turned into normal code sequences since they are field names.

Anyway, all these uses of <em> need to be scrutinized and  the source cleaned up in istio/api.

**Comment by geeknoid** [comment]
Fixed
