### ISSUE TITLE
[Kiali] put back a couple settings that were accidentally deleted in previous PR

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio.io#3660]
@johnma14 can you put these settings back? Looks like you accidentally removed them in your PR https://github.com/istio/istio.io/pull/3188 -- see here where the lines are deleted but should not be:

https://github.com/istio/istio.io/commit/149f9ddfbc34dbbf65ff009d62f22a478a2edd3a#diff-d88b59ce29807bd5e0d25dcdcd678f46L183

Put back `kiali.dashboard.jaegerURL` and `kiali.dashboard.grafanaURL`

This was first reported here: https://github.com/istio/istio.io/issues/3094#issuecomment-472361054

**Comment by linsun** [comment]
@johnma14 could you look into this?  Many thanks.

**Comment by johnma14** [comment]
@linsun @jmazzitelli I will take a look at this and push a fix soon

**Comment by johnma14** [comment]
@jmazzitelli @linsun with the latest changes made to the script that generates this index.md, we read the values.yaml file for a given configuration option from its corresponding charts directory (for e.g:, in the case of kiali, we read the key-values from /istio/install/kubernetes/helm/istio/charts/kiali/values.yaml file. In this file, https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/charts/kiali/values.yaml#L33 those values are commented out, which is why it did not show up in the index.md for release-1.1. If these key-value-descriptions of kaili from release-1.0 is still valid, shall I go ahead and update the kiali/values.yaml file to reflect it, so that this will be correctly generated in the latest index.md. Thanks.

**Comment by jmazzitelli** [comment]
@johnma14 Just so I understand clearly, the istio.io docs will only show values in the table if they exist in the chart values.yaml? Is that correct?

If so, then I guess we should uncomment (but leave the values empty) in the kiali values.yaml so they show up in the istio.io docs.

While I am here, the comments in that values.yaml is not correct. Where it says:

```
# Override the automatically detected ...
```

Kiali no longer automatically tries to detect these URLs. In the future, the Kiali team is going to try to resurrect that functionality of auto-detecting the URLs, but for the Kiali release used in Istio 1.1, that isn't happening. So we should remove those comments here.

The descriptions in the deleted lines for jaegerURL and grafanaURL are the more proper descriptions that should be used.

**Comment by johnma14** [comment]
@jmazzitelli you understood it correct regarding how we process the configuration option values. I will go ahead and update the values.yaml file for kiali to reflect the exact value and description as in release-1.0 for grafana and jaguarURL. Should I do the same for the other options as well or just those 2?

**Comment by jmazzitelli** [comment]
Kiali set up is different in istio 1.0 versus 1.1. So when in doubt, look at the release-1.1 (or master branch since release -1.1 has been merged in the master recently).

Just do the grafanaURL and jaegerURL - I think those are the only ones that need fixing.

Note that for the demo.yaml and demo-auth.yaml, both kiali.enabled and kiali.createDemoSecret will have defaults of true. We turn those on when the user wants to install the demo profile via the demo and demo-auth yaml. So that would be good to mention in the description field.

**Comment by johnma14** [comment]
This was fixed and merged in this PR: https://github.com/istio/istio/pull/12472. So closing it. Thanks.
