### ISSUE TITLE
when the site infra has a scrollbar - the text doesn't render properly

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#3972]
From the page:

https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/#deploy-the-istio-control-plane-in-each-cluster

This can be worked around with `\` but it would be nice if the text was shown.

<img width="759" alt="Screen Shot 2019-04-09 at 10 53 22 AM" src="https://user-images.githubusercontent.com/755849/55823129-ee978a80-5ab5-11e9-801b-c015357d98bd.png">

**Comment by geeknoid** [comment]
This is a Mac-induced problem, related to the "Show scroll bars" option from the System Preferences -> General page. If you set that option to "Always" then it'll work fine. With either of the other two options, the browser will not reserve any room for the scroll bar so when it's time to draw one it needs to use the main area of the text box for this purpose.

It's a recurring problem you'll see on many web sites.

This is really a browser problem in how they implement the macOS behavior, so I'm going to close this issue since there's nothing I can do about it.
