### ISSUE TITLE
remove --set global.outboundTrafficPolicy.mode=ALLOW_ANY --set pilot.env.PILOT_ENABLE_FALLTHROUGH_ROUTE=1 from the egress boilerplate

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.io#3989]

**Comment by frankbu** [comment]
@vadimeisenbergibm My thought was that this might only be a temporary check, since after 1.1.3 these are supposed to be the default settings, so it is just verifying what should be set by default. If other examples want something other than the default, I think that they can't really use this boilerplate anyway. 

Which tasks/examples want something other than the default? Maybe we should take out the install Istio part of the boilerplate and let each task/example explicitly add their own install step, and then use the boilerplate for the rest. WDYT?

**Comment by vadimeisenbergibm** [comment]
@frankbu This check is irrelevant for all other examples, so why should the user perform it? You can just move this check out of the boiler plate and put it into the egress task after the boiler plate.

The examples: https://istio.io/docs/examples/advanced-gateways/egress-gateway/#before-you-begin, https://istio.io/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/#before-you-begin. These examples work with any setting, so the check is irrelevant for them.

**Comment by frankbu** [comment]
Fixed with #3994
