### ISSUE TITLE
Demo install has unneeded step

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#3993]
https://istio.io/docs/setup/kubernetes/install/kubernetes/

The page recommends installing CRDs first, but the istio-demo.yaml already has the CRDs. Unless these actually need to be applied separately we should remove the CRD step to make it a one step install.

**Comment by frankbu** [comment]
We can remove the unneeded CRD installation step if we are creating them in istio-demo.yaml too. 
But, the bigger problem is that by [creating the CRDs](https://github.com/istio/istio/blob/6089adf96580abed81f56fb7f87bc78d78a5bdd8/Makefile#L652) (and the namespace, for that matter) in istio-demo.yaml, the documented uninstall step doesn't work properly.

The `kubectl delete -f install/kubernetes/istio-demo.yaml` command will delete the ns and the CRDs before attempting to uninstall instances of those CRDs, so even though everything does seem to get deleted (probably because the ns is deleted), the command outputs a lot of error messages. The fundamental problem is that there is an order dependency of the resources in the istio-demo.yaml, so delete needs to reverse the order.

**Comment by sdake** [comment]
@frankb just replaying a conversation we had on slack a few weeks about this topic.

The build system produces these demo manifests by cattiing the namespace, then the crds, then the contents  of the helm templated manifest.

To remove this error, the only option I can think of is to reverse the order of the operations in the creation of a new "demo-uninstall" manifest.  This is a core problem with Kuberenetes, not really with our installation procedure.  Even this approach would not work 100% of the time.  It still looks sloppy.  It is unclear to me which approach appears more sloppy.  They are both sloppy imo :)

Perhaps we should just document that the demo manifests will produce errors during uninstall because the  namespace is deleted (btw @frankb, your assessment is correct).

Deleting the namespace itself is problematic as a removal step as sometimes the sidecar injector registration stays registered (iirc) because of a defect in Kuberenetes.

**Comment by sdake** [comment]
@howardjohn - while the demo will generally work without a separate crd registration step if the crds are recorded in the manifest, it is not a 100% guarantee.  I believe k8s 1.14 fixed this problem so that CRDs are registered first, and the rest of the manifest is then applied, but I can't find the said change in the Kubernetes change logs.  As Istio 1.1 does not support 1.14, it doesn't matter.

The safest course of action is what is documented for this reason.

I am closing this bug.  If you feel this issue has been closed in error, please feel free to reopen the issue.

**Comment by linsun** [comment]
@howardjohn  i asked the exact questions a while back, it is good to have this why documented here!
