### ISSUE TITLE
Quick Start Evaluation Install instructions are broken

### ISSUE THREAD

**Issue by afeddersen** [istio/istio.io#4160]
Page: https://istio.io/docs/setup/kubernetes/install/kubernetes/

At step 2 it instructs you to Install one of the following variants of the demo profile:

install/kubernetes/istio-demo.yaml
install/kubernetes/istio-demo-auth.yaml

That directory does not exist.

**Comment by satyajitmails** [comment]
Hi Folks,

I am facing the same issues here .Any pointers/help will be appreciated.

**Comment by afeddersen** [comment]
The README.md at istio/install/kubernetes/ suggests following the quickstart at https://istio.io/docs/setup/kubernetes/quick-start.html but that page 404s.

**Comment by frankbu** [comment]
The directory `install/kubernetes` does exist. If you meant that the yaml files do not exist, what release or build did you download? Note that if you just download the source from github, those files do not exist. They are only generated and added in the release images. Note that you can use the helm instructions to install from the github source, if you don't want to download a release build.

Thanks for pointing out the bad link. The README.md is outdated and needs to be updated. It should point to https://istio.io/docs/setup/kubernetes/install/

**Comment by afeddersen** [comment]
@frankbu - As far as I can tell the quick start instructions don't mention anything about generating the files.  https://istio.io/docs/setup/kubernetes/install/kubernetes/

The guide says you don't need Helm for the demo.  It also says you can simply download the repo and do the demo install using `kubectl apply -f install/kubernetes/istio-demo.yaml`.

Thanks for the tips on the actual steps.  I think the documentation could be updated to reflect the intended process.

**Comment by frankbu** [comment]
>  It also says you can simply download the repo and ...

@afeddersen, I think the confusion here is that it does not say you can download the "repo", it says download the "release": https://istio.io/docs/setup/kubernetes/install/kubernetes/#prerequisites

The difference is that the pregenerated yaml files, `istio-demo.yaml` and `istio-demo-auth.yaml`, are only available in the release image, not in the source repo. So, if you want to use the github repo, instead of a release to run the demo, you need to use the helm instructions to install: https://istio.io/docs/setup/kubernetes/install/helm/#option-1-install-with-helm-via-helm-template

Note that when using the github repo master branch, you will be running code that is not guaranteed to be fully tested and the corresponding documentation is in https://preliminary.istio.io, not https://istio.io.

I'll update the documentation to make this a little more clear.
