### ISSUE TITLE
Exercise section Fault Injection Task is too specific on the time delay that could work

### ISSUE THREAD

**Issue by bhaskar-reddy** [istio/istio.io#4343]
Not a big deal of an issue, but the [Exercise](https://preliminary.istio.io/docs/tasks/traffic-management/fault-injection/#exercise) section of the _Fault Injection Task_ asks user to change the Fault Injection delay to 2.8s and give it a try:

> Change the delay rule to use a 2.8 second delay and then run it against the v3 version of reviews.

But when I tried with that setting, I was still getting the error:

> Error fetching product reviews!
> Sorry, product reviews are currently unavailable for this book.

After a bit of playing with the timing, I was able to get it to work at 2.5s often and at 2.4s consistently, while at 2.6s it was throwing the error again.

So, it might be worth it to have verbiage updated accordingly. Maybe, _change delay to 2.5s_.. while also mentioning about _each system could vary by a few milliseconds_ or something along those lines.

**Comment by frankbu** [comment]
The exercise is suggesting 2.8 seconds, because that is a value greater than 2.5 secs (the reviews:v3->ratings) timeout, but less than 3 seconds which is the productpage->reviews timeout. As a result, the call to reviews should succeed, but the call from reviews to ratings will timeout. This is supposed to result in the UI displaying the reviews, but next to each review is an error message stating that the ratings are currently not available. If that's not the case, it sounds like the bookinfo application has been changed recently, causing it not to work properly. There have been various changes to the app to make it more REST-like, but the behavior was supposed to be unchanged.

If this is the case, this appears to be a sample bug, not a doc problem, although it probably makes sense to update the doc to explain what the exercise is trying to show. Right now, it's totally unclear what the user should expect to see with the 2.8 sec delay.

**Comment by bhaskar-reddy** [comment]
Thank you for the explanation. 
Please note that the task doesn't mention the timeout for reviews:v3->ratings. So, I do think the doc needs more clarity on informing the operator on various timeouts with different versions. As well as different delays we are trying to induce as part of the task. And at what induced delay will the timeout get triggered (or not).

**Comment by frankbu** [comment]
After looking at the reviews service implementation, I see that the implementation has at some point been changed and does not work like it used to in the past. It used to call the ratings service and if the request timed out it would handle the error and then send back the properly formatted response body containing the reviews, but the ratings set to indicate that they were unavailable. That way, the productpage would then be display the reviews, but next to each review was a message indicating `ratings are not currently available`, instead of the ratings stars. The current version of reviews, however, is instead returning an error back to reviews, indicating it failed because of the ratings service timeout. That's why the exercise with a 2.8 second delay is no longer working as it used to, so it's not particularly interesting anymore.

So, unless and until the reviews service is fixed to handle the ratings timeout properly, like it used to, I think the best thing to do is just remove the 2.8 sec delay exercise from the task for now. We can add it back (with a proper explanation of what it's doing) in the future, after we've fixed the code.
