### ISSUE TITLE
Setting istio sidecar proxy resource request/limit

### ISSUE THREAD

**Issue by sebarys** [istio/istio.io#4769]
Hello :)

Is there an option to set istio proxy sidecar request/limits per application (`Pod`)? For some of our applications we would like to use `Guaranteed` QoS (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) that require setting `limit == request` for all Pod containers. Without such functionality we're loosing this feature.

Thanks for help in advance!

**Comment by ostromart** [comment]
Hi, that is currently available through the helm passthrough API in the operator, so you could write:
trafficManagement:
  components:
    proxy:
      values:
        resources:
          requests:
           cpu: <your values>
This will pass through to the sidecar injector template.
We're also working on being able to use the common k8s struct for the injector template, so you'll be able to use:
trafficManagement:
  components:
    proxy:
      k8s:
        resources:
          requests:
           cpu: <your values>
The latter would be preferred going forward because k8s field gives you full access to setting k8s resources using the k8s API.

**Comment by sebarys** [comment]
Hi @ostromart, thanks for info.
Unfortunately I think it not solve my problem as it is the global config value and if I understood correctly it could be used only during Istio installation, not applied for each Pod separately.
Some of our applications have bigger traffic so need higher requested `resource` values, other lower. As istio-proxy resources are somehow proportional to application container resources (e.g. one application is handling much bigger traffic than another -> it will require more resources also on istio-proxy sidecar layer) I would like to have an option to align resources assigned to isito-proxy per Pod.

**Comment by BradErz** [comment]
Did you understand the best way of doing this @sebarys ?

My current line of thought is we can disable the automatic injection on the apps which have more throughput and manually add in the istio-init and istio-proxy components to the deployment.

We have one application that does a lot of RPS and simply isn't enough as the pod can be scheduled on a node where it only has access to 100m instead of the 2 cores it will need. 
 ```yaml      
requests:
  cpu: 100m
  memory: 128Mi
```

But these limits make sense for the other 98% of our applications.

Does anyone else have a better way of solving this? Could it be something that we can add to the istio-sidecar-injector and based off of a label on the deployment override the values specified in the configmap?

**Comment by BradErz** [comment]
nvm.. seems it is possibe, just not documented really anywhere that i could see. If someone has a suggestion of where it would be best suited to add this doc i can do it in the morning.

https://github.com/istio/istio/blob/90ebc30554a21c54a4d38b9b225e877a6e74270f/pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected#L14-L16
