### ISSUE TITLE
Document what users's control plane should be after installation

### ISSUE THREAD

**Issue by jwendell** [istio/istio.io#5298]
Should we document, in the install page, the expected state of the control plane after the installation?

For example:

This is what you should expect when you install using the default profile:
```
kubectl -n istio-system get pods
<RESULT>
```
And, when we tell users about the demo profile, do the same.

It was confusing not to see the proxy containers on pilot and mixer pods. I spent some time trying to figure out why. Turns out that's because I installed the demo profile, and that's expected.

**Comment by frankbu** [comment]
We do show the expected services/pods in the [getting-started instructions](https://istio.io/docs/setup/getting-started/#install), so new users can see what Istio is doing to their cluster. In the [general instructions](https://istio.io/docs/setup/install/istioctl/), for people ready to try more advanced configuration options, I think that would be too much noise.

For your particular problem, I wonder if it would make sense to add some doc somewhere (FAQ) to explain that the control plane pods will have 2 containers if you configure, or select a profile that configures, global.controlPlaneSecurityEnabled=true. Otherwise they will have 1 container.

**Comment by howardjohn** [comment]
this is added now https://istio.io/latest/docs/setup/install/istioctl/#check-what-s-installed
