### ISSUE TITLE
Issue with docs/setup/install/istioctl/index.md

### ISSUE THREAD

**Issue by eperdeme** [istio/istio.io#5716]
The example does not look to work.

```
istioctl manifest apply -f test.yaml                                
Failed to generate and apply manifests, error: failed to generate manifest: could not unmarshal the overlay file: unknown field "namespace" in v1alpha2.SecurityFeatureSpec

Original YAML:
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  defaultNamespace: istio-system
  security:
    namespace: istio-security
    components:
      citadel:
        namespace: istio-citadel

```

client version: 1.4.0
control plane version: 1.4.0
data plane version: none

**Comment by denniseffing** [comment]
There are actually atleast two issues with this: 
1. The field `namespace` is not supported for the API `v1alpha2.SecurityFeatureSpec`
2. Even when removing the namespace field, Istio installation fails because `istioctl` does not automatically create the provided namespace. The namespace must exist beforehand.

```
Component Citadel failed install:
=================================
Error: error running kubectl: exit status 1

Error detail:

Error from server (NotFound): error when creating "STDIN": namespaces "istio-citadel" not found (repeated 4 times)
```

Istio operator installation should also be tested for (2).

**Comment by esnible** [comment]
The only place I still see this is in the Chinese documentation file _content/zh/docs/setup/install/istioctl/index.md_.

Fixed by @myidpt in https://github.com/istio/istio.io/pull/7872
