### ISSUE TITLE
Issue with istio.io web site's internationalization.

### ISSUE THREAD

**Issue by Aisuko** [istio/istio.io#6062]
There was some issue with website internationalization. Please do some checks with the URL below.

* https://istio.io/zh/  (the current releasing version is 1.4)
* https://archive.istio.io/v1.3/zh/

Issue:

  Can not reach the website page, and get the error message below.

`The URL may be misspelled or the page you're looking for is no longer available`

**Comment by geeknoid** [comment]
Chinese translation has been disabled for a while now since the translated content hadn't been updated. A lot of working has been going into doing a fresh translation, which will hopefully be ready and released with Istio 1.5 or shortly thereafter.

So I'm closing this issue. Sorry for the inconvenience.
