### ISSUE TITLE
Inconsistent Capitalization in the Command Reference

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#6359]
Looking at: https://preliminary.istio.io/docs/reference/commands/istioctl/
the capitalization of sentences is very inconsistent. Some sentences start with a capital letter, but there are many that do not. 

Examples: 
`istioctl experimental add-to-mesh external-service create a ServiceEntry and\ a Service without selector for the specified external service in Istio service mesh. The typical usage scenario is Mesh Expansion on VMs. THIS COMMAND IS STILL UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.`

`istioctl experimental add-to-mesh service restarts pods with the Istio sidecar. Use 'add-to-mesh' to test deployments for compatibility with Istio. If your service does not function after using 'add-to-mesh' you must re-deploy it and troubleshoot it for Istio compatibility. See https://istio.io/docs/setup/kubernetes/additional-setup/requirements/ THIS COMMAND IS STILL UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.`

`(convert-ingress has graduated. Use `istioctl convert-ingress`)`

`webhook command to manage webhook configurations`

There are quite a few other instances as well.

**Comment by ericvn** [comment]
@esnible I believe the changes requested here would actually be changes to the `Long:` descriptions in the commands in istio:istio/istioctl/cmd files. I also notice the \ at the end of one of the lines.

**Comment by esnible** [comment]
@brian-avery The documentation is auto-generated, as @ericvn says, from the `Long:` text that is shown when a user does `istioctl <cmd> --help`.

I will check these sentences for compatibility with the Style Guide https://istio.io/about/contribute/style-guide/

Because the text must be output by _istioctl_ it cannot contain markdown.  I can't say "`istioctl experimental add-to-mesh service` restarts pods with the Istio sidecar."  I could put single quotes or backticks around the text, perhaps.

Do you think the kind of improvements we can make by changing the _istioctl_ code will be sufficient?  If we give up using the code to generate the documentation we gain the ability to use things like `<code>` in the docs but it becomes a headache to keep the CLI and documentation in sync.

**Comment by brian-avery** [comment]
Yeah, I assumed this was auto generated. I think that the changes we can make for `istioctl` should be sufficient. I was just proposing using complete sentences with capitalization instead of fragments.
