### ISSUE TITLE
Add note on Istio Standard Metrics page for multi-cluster

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#7286]
Non-blocking.

We should update the Istio Standard Metrics page to include a note about the following dimensions:
- `destination_cluster`
- `source_cluster`

They are only included in multi-cluster scenarios.

/cc @nmittler @frankbu

**Comment by nmittler** [comment]
Ideally, these metrics should just always be included rather than being special-cased for multicluster. We're moving toward a model where multicluster is the default configuration WRT docs. Already, the multicluster install docs for 1.6 are configuring the first cluster in such a way that it will work with multicluster and vms. These docs will (very soon) completely replace the installation guides for Istio.

FYI @smawson
