### ISSUE TITLE
Require 2 approvers for any istio.io blogs

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#7535]
In one of the @istio/steering-committee meetings, it was decided we need 1 doc maintainer approval plus 1 additional approver from a steering committee member to ensure the blog content is technical and appropriate for istio.io without too much marketing information.

cc @nrjpoddar @rshriram @frankbu FYI

**Comment by nrjpoddar** [comment]
Thanks @linsun for letting us know. This change makes perfect sense to ensure quality and fairness in the community!

**Comment by frankbu** [comment]
Although good to add the approval requirement, the more important question is how to decide. 

Some cases are pretty clear, but there is a large grey area of blogs that may look like advertising but are also a legitimate example of integration with Istio. This issue came up today, because of [this PR](https://github.com/istio/istio.io/pull/7520#issuecomment-642698599). My main objection is is that even though it claims to be focusing on Kong's integration with service mesh, there's nothing in it that explains how it works with Istio other than a picture of bookinfo services. The productpage could just as easily be running in plain Kube for the demo in the blog. It doesn't even mention Istio Gateway, and what  replacing it with Kong actually changes.

But, as @rshriram pointed out to me, if that was fixed, then you could easily look at the blog as either advertising or as an article about plugging in an existing ingress controllers to make it work with Istio.

**Comment by linsun** [comment]
Looks like we won't have an easy way to require 2 approvers in GitHub for a certain folder in a repo (we know how to do it for the entire istio.io repo) so it will rely on the steering member to do the check to see if the blog is appropriate or too much marketing/vendor info and request 1 doc maintainer approval as needed.  We do expect "blog published this week" to be on steering weekly agenda so it will be mentioned as FYI.  When there is doubt with any blog, the  reviewer from the steering committee should put the blog on hold till it is reviewed in the weekly steering meeting.

cc @istio/steering-committee

**Comment by sdake** [comment]
@linsun would you mind modifying https://github.com/istio/community/blob/master/CONTRIBUTING.md to indicate this ruling? I think this would help slim down the number of adverts that come in as blog posts - assuming people read the contributing guidelines.

I often struggle with approving blog posts on istio.io in the past - because the line between vendor plug and legitimate integration information can sometimes be very narrow.

Cheers,
-steve

**Comment by linsun** [comment]
closing this as too old no longer relevant
