### ISSUE TITLE
Document how to run istio on minikube without RBAC?

### ISSUE THREAD

**Issue by hmalphettes** [istio/istio.io#784]
Hi! Thanks again for maintaining the istio documentation.

I noticed that I could install istio on minikube without RBAC: I removed the definitions of `ClusterRole` and `ClusterRoleBinding` from the `install/kubernetes/istio.yaml`.
The Bookinfo app and telemetry are working fine.

minikube and other local setups are installed with RBAC by default currently.
Beside the setup of minikube, diving into istio and RBAC at the same time makes istio a bigger pill to swallow at once.

Is a no-RBAC setup something that deserves to be documented or is it a dead-end?

Thanks for your attention!

**Comment by sdake** [comment]
@hmalphettes apologies for the long delay in responding to this issue.  Is this currently desirable after the big gap in time between the submission of this RFE and today?

The Istio community highly recommends production deployments use RBAC, RBAC is highly stable in both Kuberentes and Istio's implementation, and generally developers prefer to test one scenario (RBAC on) vs two (RBAC on / RBAC off)l

The stability of RBAC was highly questionable when you submited the issue in Deembher 2017 when this issue was filed - so understand the big pill argument :)  Do you still feel this is the case?

Cheers
-steve

**Comment by sdake** [comment]
@ironstine @mwjsanders ^^

**Comment by sdake** [comment]
Istio requires RBAC.  Closing this issue as there is no way to run Istio sans RBAC.
