### ISSUE TITLE
Correct hanging reference in VM Docs

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio.io#7853]
https://github.com/istio/istio.io/blob/master/content/en/docs/examples/virtual-machines/multi-network/index.md#preparing-the-kubernetes-cluster-for-vms

In Step 1, the grammar indicates that there will be instructions following the step, but there are no instructions.  Instructions should be added, or the wording changed.

**Comment by jasonwzm** [comment]
We were discussing this before. Assigning to myself, Limin and John to work on the current VM docs.

**Comment by duderino** [comment]
Looks like https://github.com/istio/istio.io/commit/479b4b161cec6427d37aab3cc642f2795b9a1d3c#diff-66df94b4108652e624a42b21d8bc3394 unintentionally deleted the example?  @adammil2000 was this intentional?

**Comment by duderino** [comment]
Since this is a release blocker, let's have a single owner so we don't have a diffusion of responsibility problem.  Jason, I think you can satisfy this blocker by just restoring the missing example in my prior comment.  A general revamp of the VM docs would be welcome, but it wouldn't block the 1.7 release.

Also, if you don't think you're a good fit for this please let me know so I can find another owner.

**Comment by jasonwzm** [comment]
@duderino sounds good. I think in TOC meeting we also mentioned the single network setup instruction is not working. Is that a release blocker as well?

**Comment by liminw** [comment]
Sounds good. Jason, let me know if you need help on security setup. /cc @williamaronli also has context since he worked on VM identity bootstrapping for 1.7.
