### ISSUE TITLE
http 404 for hyperlink in page https://istio.io/latest/docs/setup/getting-started/#dashboard

### ISSUE THREAD

**Issue by didier-durand** [istio/istio.io#8139]
Hello,

In page of title, the URL behind "kubectl apply -f samples/addons" which is https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons currently gives http 404.

Didier

**Comment by shamsher31** [comment]
Ref: https://istio.io/latest/docs/setup/getting-started/#dashboard

If you look into the samples folder.

```
[istio-1.7.0]$ ls samples/addons/
extras  grafana.yaml  jaeger.yaml  kiali.yaml  prometheus.yaml  README.md
```

> Use the following instructions to deploy the Kiali dashboard, along with Prometheus, Grafana, and Jaeger.

As per the instruction, the following command will install everything from  `samples/addon` folder.

```
$ kubectl apply -f samples/addons
```

**So that URL was never meant to be clicked** but to allow all addons to be installed from that location.

You can find more details here.
https://github.com/istio/istio/tree/release-1.7/samples/addons

**Comment by didier-durand** [comment]
Ok, thanks. Though, I thought that it would be good for the document to be clickable to make things easier. 
Didier
