### ISSUE TITLE
How to setup envoy proxy with custom certs

### ISSUE THREAD

**Issue by rambo45** [istio/istio.io#832]
I would like to setup envoy proxy with custom certs for services instead of using Istio-CA generated certs. Please provide examples to achieve that.

This is a common scenario where there is an organization policy to use private certs generated by a central certificate authority. Any http service should be use those certs generated by that CA. Is it possible to do that with Istio?

**Comment by wattli** [comment]
So far this is not supported. Customer can pass their root cert when installing Citadel (Istio CA). But so far we don't have plan to support external CA issuing Istio certs directly.

**Comment by myidpt** [comment]
You can plug in your CA signing cert and key into Citadel: https://preliminary.istio.io/docs/tasks/security/plugin-ca-cert/

**Comment by costinm** [comment]
Updating the bug as well: networking allows the use of any certificate or CA, as long as the file is mounted in the sidecar in the expected location. Destination rules allow control over client verification, and server will load any cert type.

The actual requirement that some parts of the system have is on having spiffe URL SAN.

**Comment by sdake** [comment]
@myidpt did the implementation make the 1.0 release?  I seem to recall it did as I'm pretty sure I tested this scenario prior to July and have not since, but YMMV on dependence on my memory :).  If so, we may wish to backport the documentation (if not already backported and a backport is feasible).  If not, looks documented for 1.1 and this issue could be closed.

@rambo45 are you satisfied with the existing documentation pointed out by @myidpt?

Cheers
-steve

**Comment by vigneshrockfort** [comment]
is this issue resolved/workaround in the latest version of istio? We have a similar scenario, we want to use our own server certificates instead of istio-generated certs. Please let me know if there is a way to achieve this
