### ISSUE TITLE
Add support to test framework to use the same test environment across to test multiple docs

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#8429]
The current test framework environment supports setting up an Istio environment and deleting the resources created when testing the functionality on a page. In cases where we have to use the same environment across multiple docs, the test framework does not support that scenario. An example where this support is needed is the "Learn Microservices using Kubernetes and Istio" example ( https://istio.io/latest/docs/examples/microservices-istio/) where we need to build on the test environment across multiple pages.

**Comment by johnma14** [comment]
@frankbu @ericvn @nmittler thoughts?

**Comment by nmittler** [comment]
IIUC, I think what we want here is sub-tests.

We might be able to modify the framework to recognize this parent/child relationship with our tests. Something like:

- parent **(indicates it's a parent in the metadata)**
  - test (can be empty)
  - cleanup **(added steps for any child cleanup as necessary)**
  - child1 (indicates subtest in metadata)
    - **order**: defines the order of execution of the subtest
    - test
    - cleanup (called when this subtest completes)
  - child2 (indicates subtest in metadata)
    - **order**
    - test
    - cleanup

New things in bold. Subtests would have to be able to specify an order in which their run WRT each other. The parent/child relationship would be established by the metadata in `test.sh`, similar to what is done for selecting the profile today. There are two levels of cleanup: each subtest can perform cleanup steps, or let the parent do it. The test author will have to manually choose where to put cleanup logic in order to make the subtests work properly together.

The lifecycle would then be:

- parent test
- child test
- child cleanup
- ... // more children
- parent cleanup

WDYT?

**Comment by johnma14** [comment]
This sounds reasonable to me @nmittler

**Comment by howardjohn** [comment]
this is done now
