### ISSUE TITLE
Clarify multicluster install docs

### ISSUE THREAD

**Issue by nmittler** [istio/istio.io#8488]
- For multi-network install docs, we should be more explicit indicating that you need one east-west per network.
- Be clear stating that each primary needs the secrets for all the clusters.

**Comment by stevenctl** [comment]
I think this is done.

**Comment by nmittler** [comment]
@smawson IIRC you had originally asked for this? Do you mind reviewing the current docs and see if it provides what you were asking for?

**Comment by smawson** [comment]
Looking at the current docs I don't actually think this is done. Basically the problem is that our docs don't scale well to larger meshes, because they don't tell you what things need to happen on every primary vs. every remote vs. once per network. It just isn't obvious as a reader.

Somewhere there needs to be general guidance on how to manage a large multi-cluster, multi-network mesh, that talks about the requirements for each cluster in the mesh.

**Comment by stevenctl** [comment]
#8605 will tackle that.
