### ISSUE TITLE
"Edit this page" button opens editor on the branch

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#8979]
I found a broken page on istio.io and then hit the "edit this page on GitHub" link, which took me to 
`https://github.com/istio/istio.io/edit/`**`release-1.9`**`/content/en/docs/tasks/observability/metrics/classify-metrics/index.md` - not master.

When I realised that the diff was against release-1.9 in the PR creation process, I changed it to master, but now it's out of sync. 

For drive-by contributions such as these, should we make the "edit in GitHub" open on master?

**Comment by ericvn** [comment]
The problem is that istio.io shows what's in the release-1.9 branch. If the page was updated for 1.10, the user could see something wildly different, and wouldn't understand what needed to be change.

I think we need to keep it on the same branch that is being displayed. Normally, we will cherrypick these back to the master branch (incumbent on the reviewer to not that the PR is for release-1.9 and isn't a cherry-pick and add the label).
