### ISSUE TITLE
Lint checks rendered output for blockquote tags

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9369]
We put {{< quote >}} in Markdown and the rendered HTML in /public should contain `<blockquote>` elements.

https://github.com/istio/istio.io/blob/master/scripts/lint_site.sh#L171 appears to me to look at the rendered HTML output and complain if it has blockquote elements.

Should this check be run on the content directory instead of the public directory?

`<(find ./content "${find_exclude[@]}" -type f -name '*.md' -print0)` perhaps?

**Comment by davidhauck** [comment]
Seems like the problem is due to the fact that polidea has added blockquotes to {{ quote }} and case studies (https://github.com/istio/istio.io/blob/polidea-update/layouts/shortcodes/quote.html). This isn't merged into master / release branches yet as far as I can tell. We need to ensure the linter is successful before merging.

If we're planning on actually using blockquotes, then it would probably be best to just remove this check

**Comment by craigbox** [comment]
Right, I follow; it's not about `<blockquote>` elements in the new content directly, it's that the new template turned `{{< quote >}}` into blockquote, and not `<div class="quote">` or whatever was expected.

Polidea have fixed this up and it makes sense now.
