### ISSUE TITLE
Istio namespace not found

### ISSUE THREAD

**Issue by prary** [istio/istio.io#9892]
Hi, 

Installing istio operator way throws the following error.

```
arya@arya-Inspiron-5559:~/istio-1.9.0$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
Error from server (NotFound): error when creating "STDIN": namespaces "istio-system" not found
```

[Docunmentation](https://istio.io/latest/docs/setup/install/operator/#install ) either misses ```kubectl create ns istio-system```
or there is typo. Instead of ```kubectl apply``` if we use istioctl then it works fine.
'''
arya@arya-Inspiron-5559:~/istio-1.9.0$ istioctl apply -f install.yaml 
This will install the Istio 1.9.0 demo profile with ["Istio core" "Istiod" "Ingress gateways" "Egress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed                                                                                                                                                                                     
✔ Istiod installed                                                                                                                                                                                         
✔ Egress gateways installed                                                                                                                                                                                
✔ Ingress gateways installed                                                                                                                                                                               
✔ Installation complete     
```
In case it's a typo then we need to update the kubectl with istioctl on all the example of this page.
Will raise the PR just help me with the right choice.

**Comment by prary** [comment]
@howardjohn  Do you mind if I raise the PR for it?

**Comment by howardjohn** [comment]
Sure!

**Comment by ericvn** [comment]
See https://github.com/istio/istio.io/pull/9111 which removed the namespace creation from that page. It appears that Istio 1.10 does indeed create the namespace. You mention 1.9 above. The 1.9 version of the docs, https://istio.io/v1.9/docs/setup/install/operator/, does include the namespace creation.

**Comment by ericvn** [comment]
That said, the page does have a message about changes made in 1.9 to no longer require some arguments. One may want to add a similar style message after the `istioctl operator init` mentioning that prior to 1.10 the name space needs to be created.

**Comment by syedrakib** [comment]
## Steps to reproduce the error

I deleted all istio namespaces from my GKE cluster

```bash
$ kubectl delete namespace istio-operator istio-system
```

Installed **istioctl version 1.10.2** in MacOS following https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/?_ga=2.53425067.2032442266.1631216965-1634768249.1631055742#install-hahahugoshortcode-s2-hbhb

Then installed istio-operator

```bash
$ istioctl operator dump > operator_dump.yaml
$ kubectl apply -f operator_dump.yaml
```

Confirmed that the istio-operator is up & running

```bash
$ kubectl rollout status deployment/istio-operator -n=istio-operator
deployment "istio-operator" successfully rolled out
```

## The Error

The next step involves applying the IstioOperator CRD following https://istio.io/latest/docs/setup/install/operator/?_ga=2.63248428.2032442266.1631216965-1634768249.1631055742#install

```bash
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```

At this point i expect it to just work. But i got the following error:

```
Error from server (NotFound): error when creating "STDIN": namespaces "istio-system" not found
```

## Docs say otherwise

The docs at https://istio.io/latest/docs/setup/install/operator/?_ga=2.233666461.2032442266.1631216965-1634768249.1631055742#install says 

> Prior to Istio 1.10.0, the namespace istio-system needs to be created before installing the operator. As of Istio 1.10.0, this is no longer required.

---

Looks like the istio operator needs a fix or the docs needs to be revised.
